Layout/LineLength:
  Max: 125
Style/Documentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/**/*.rb"
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - Gemfile
    - node_modules/node-sass/src/libsass/contrib/*
    - node_modules/node-sass/src/libsass/*
    - bin/bundle
    - node_modules/@prettier/plugin-ruby/*
    - node_modules/@prettier/plugin-ruby/src/*
    - node_modules/@prettier/plugin-ruby/src/haml/*
    - node_modules/@prettier/plugin-ruby/bin/*
    - vendor/**/*
