version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: node-modules-v1-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec rubocop
      - run: rails format:check
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: node-modules-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - test
