version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: node-modules-v1-{{ checksum "package-lock.json" }}
      - run: yarn
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec rubocop
      - run: rails format:check
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: node-modules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - test

- restore_cache:
    keys:
      - v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
      # if cache for exact version of `project.clj` is not present then load any most recent one
      - v1-myapp-
