version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - restore_cache:
        keys:
          - gem-cache-v1-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1
      - restore_cache:
        keys:
          - node-modules-v1-{{ checksum "package-lock.json" }}
          - node-modules-v1
      - checkout
      - run: yarn
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec rubocop
      - run: rails format:check
      - save_cache:
        key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - save_cache:
        key: node-modules-v1-{{ checksum "package-lock.json" }}
        paths:
          - node_modules

workflows:
  version: 2
  build:
    jobs:
      - test
