version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: node-modules-v2-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: bundle install --jobs=1 --retry=3 --path vendor/bundle
      - save_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: node-modules-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: bundle exec rspec
      - run: bundle exec rubocop
      - run: bin/rails format:check

workflows:
  version: 2
  build:
    jobs:
      - test
